<?php
session_start();
require_once __DIR__ . '/includes/db.php';

// Access control
if (!isset($_SESSION['user_id']) || !in_array($_SESSION['role'], ['admin', 'assistant'])) {
    require_once __DIR__ . '/includes/header.php';
    echo "<div class='alert alert-warning text-center mt-5'><h4>Access Restricted</h4><p>You do not have permission to view this page.</p></div>";
    require_once __DIR__ . '/includes/footer.php';
    exit();
}

// === HANDLE EXPORT (Kept exactly as your original code) ===
if (isset($_GET['export'])) {
    $export_type = $_GET['export'];
    $date_from = $_GET['date_from'] ?? date('Y-m-01');
    $date_to = $_GET['date_to'] ?? date('Y-m-d');
    
    header('Content-Type: text/csv');
    header('Content-Disposition: attachment; filename="' . $export_type . '_report_' . date('Y-m-d') . '.csv"');
    $output = fopen('php://output', 'w');
    fputs($output, $bom =( chr(0xEF) . chr(0xBB) . chr(0xBF) ));

    if ($export_type === 'summary') {
        fputcsv($output, ['CSM APPARATUS SYSTEM - OFFICIAL SUMMARY REPORT']);
        fputcsv($output, ['Generated By: ' . $_SESSION['username']]);
        fputcsv($output, ['Date Generated: ' . date('M d, Y h:i A')]);
        fputcsv($output, ['Reporting Period: ' . date('M d, Y', strtotime($date_from)) . ' to ' . date('M d, Y', strtotime($date_to))]);
        fputcsv($output, []);
        fputcsv($output, ['METRIC', 'VALUE']);
        
        $stats = [
            'Total Requests' => mysqli_fetch_assoc(mysqli_query($conn, "SELECT COUNT(*) as c FROM borrow_requests WHERE date_requested BETWEEN '$date_from' AND '$date_to'"))['c'],
            'Approved' => mysqli_fetch_assoc(mysqli_query($conn, "SELECT COUNT(*) as c FROM borrow_requests WHERE status='approved' AND date_requested BETWEEN '$date_from' AND '$date_to'"))['c'],
            'Rejected' => mysqli_fetch_assoc(mysqli_query($conn, "SELECT COUNT(*) as c FROM borrow_requests WHERE status='rejected' AND date_requested BETWEEN '$date_from' AND '$date_to'"))['c'],
            'Pending' => mysqli_fetch_assoc(mysqli_query($conn, "SELECT COUNT(*) as c FROM borrow_requests WHERE status='pending' AND date_requested BETWEEN '$date_from' AND '$date_to'"))['c'],
            'Completed/Returned' => mysqli_fetch_assoc(mysqli_query($conn, "SELECT COUNT(*) as c FROM borrow_requests WHERE status='returned' AND date_requested BETWEEN '$date_from' AND '$date_to'"))['c'],
            'Total Penalties Collected' => number_format(mysqli_fetch_assoc(mysqli_query($conn, "SELECT COALESCE(SUM(amount), 0) as c FROM penalties WHERE date_imposed BETWEEN '$date_from' AND '$date_to'"))['c'], 2),
        ];
        
        foreach ($stats as $metric => $value) {
            fputcsv($output, [$metric, $value]);
        }
    } elseif ($export_type === 'requests') {
        fputcsv($output, ['ID', 'Student Name', 'Apparatus', 'Qty', 'Faculty', 'Date Needed', 'Date Requested', 'Status']);
        $result = mysqli_query($conn, "SELECT br.request_id, COALESCE(s.full_name, s.username) as student_name, a.name as apparatus_name, br.quantity, COALESCE(f.full_name, f.username) as faculty_name, br.date_needed, br.date_requested, br.status FROM borrow_requests br LEFT JOIN users s ON br.student_id = s.user_id LEFT JOIN apparatus a ON br.apparatus_id = a.apparatus_id LEFT JOIN users f ON br.faculty_id = f.user_id WHERE br.date_requested BETWEEN '$date_from' AND '$date_to' ORDER BY br.date_requested DESC");
        while ($row = mysqli_fetch_assoc($result)) fputcsv($output, $row);
    } elseif ($export_type === 'penalties') {
        fputcsv($output, ['ID', 'Student', 'Reason', 'Amount', 'Date Imposed', 'Status']);
        $result = mysqli_query($conn, "SELECT p.penalty_id, COALESCE(s.full_name, s.username) as student_name, p.reason, p.amount, p.date_imposed, COALESCE(p.status, 'unpaid') as status FROM penalties p LEFT JOIN transactions t ON p.transaction_id = t.transaction_id LEFT JOIN borrow_requests br ON t.request_id = br.request_id LEFT JOIN users s ON br.student_id = s.user_id WHERE p.date_imposed BETWEEN '$date_from' AND '$date_to' ORDER BY p.date_imposed DESC");
        while ($row = mysqli_fetch_assoc($result)) fputcsv($output, $row);
    }
    fclose($output);
    exit();
}

require_once __DIR__ . '/includes/header.php';

// === DATA PREPARATION ===
$default_start = date('Y-m-01');
$date_from = $_GET['date_from'] ?? $default_start;
$date_to = $_GET['date_to'] ?? date('Y-m-d');

// 1. General Stats
$total_requests = mysqli_fetch_assoc(mysqli_query($conn, "SELECT COUNT(*) as c FROM borrow_requests WHERE date_requested BETWEEN '$date_from' AND '$date_to'"))['c'];
$approved_requests = mysqli_fetch_assoc(mysqli_query($conn, "SELECT COUNT(*) as c FROM borrow_requests WHERE status='approved' AND date_requested BETWEEN '$date_from' AND '$date_to'"))['c'];
$returned_requests = mysqli_fetch_assoc(mysqli_query($conn, "SELECT COUNT(*) as c FROM borrow_requests WHERE status='returned' AND date_requested BETWEEN '$date_from' AND '$date_to'"))['c'];
$rejected_requests = mysqli_fetch_assoc(mysqli_query($conn, "SELECT COUNT(*) as c FROM borrow_requests WHERE status='rejected' AND date_requested BETWEEN '$date_from' AND '$date_to'"))['c'];
$pending_requests = mysqli_fetch_assoc(mysqli_query($conn, "SELECT COUNT(*) as c FROM borrow_requests WHERE status='pending' AND date_requested BETWEEN '$date_from' AND '$date_to'"))['c'];
$penalties_sum = mysqli_fetch_assoc(mysqli_query($conn, "SELECT COALESCE(SUM(amount), 0) as total FROM penalties WHERE date_imposed BETWEEN '$date_from' AND '$date_to'"))['total'];

// 2. Inventory Health
$total_items = mysqli_fetch_assoc(mysqli_query($conn, "SELECT COUNT(*) as c FROM apparatus"))['c'];
$low_stock_count = mysqli_fetch_assoc(mysqli_query($conn, "SELECT COUNT(*) as c FROM apparatus WHERE quantity <= 5 AND quantity > 0"))['c'];
$overdue_count = mysqli_fetch_assoc(mysqli_query($conn, "SELECT COUNT(*) as c FROM borrow_requests WHERE status IN ('released', 'approved') AND date_needed < CURDATE()"))['c'];

// 3. Most Borrowed
$top_items_query = mysqli_query($conn, "SELECT a.name, a.category, COUNT(br.request_id) as total_borrowed FROM borrow_requests br JOIN apparatus a ON br.apparatus_id = a.apparatus_id WHERE br.date_requested BETWEEN '$date_from' AND '$date_to' GROUP BY br.apparatus_id ORDER BY total_borrowed DESC LIMIT 5");

// 4. Overdue List
$overdue_list_query = mysqli_query($conn, "SELECT br.request_id, a.name as apparatus, COALESCE(u.full_name, u.username) as student, br.date_needed FROM borrow_requests br JOIN apparatus a ON br.apparatus_id = a.apparatus_id JOIN users u ON br.student_id = u.user_id WHERE br.status IN ('released', 'approved') AND br.date_needed < CURDATE() ORDER BY br.date_needed ASC");

// === 5. CHART DATA PREPARATION ===

// Chart A: Status Distribution
$chart_status_data = [
    'Approved' => $approved_requests,
    'Returned' => $returned_requests,
    'Rejected' => $rejected_requests,
    'Pending'  => $pending_requests
];

// Chart B: Daily Request Trend (Timeline)
$trend_query = mysqli_query($conn, "SELECT DATE(date_requested) as date, COUNT(*) as count FROM borrow_requests WHERE date_requested BETWEEN '$date_from' AND '$date_to' GROUP BY DATE(date_requested) ORDER BY date ASC");
$trend_labels = [];
$trend_data = [];
while($row = mysqli_fetch_assoc($trend_query)) {
    $trend_labels[] = date('M d', strtotime($row['date']));
    $trend_data[] = $row['count'];
}

// Chart C: Usage by Category
$cat_query = mysqli_query($conn, "SELECT a.category, COUNT(br.request_id) as count FROM borrow_requests br JOIN apparatus a ON br.apparatus_id = a.apparatus_id WHERE br.date_requested BETWEEN '$date_from' AND '$date_to' GROUP BY a.category");
$cat_labels = [];
$cat_data = [];
while($row = mysqli_fetch_assoc($cat_query)) {
    $cat_labels[] = $row['category'];
    $cat_data[] = $row['count'];
}
?>

<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>

<style>
    :root { --print-border: 1px solid #333; --print-text: #000; }
    .screen-controls { background: #fff; padding: 20px; border-radius: 8px; box-shadow: 0 2px 4px rgba(0,0,0,0.05); margin-bottom: 25px; }
    .report-container { background: white; padding: 40px; border-radius: 4px; max-width: 1000px; margin: 0 auto; box-shadow: 0 0 15px rgba(0,0,0,0.05); }
    .report-header { text-align: center; margin-bottom: 30px; border-bottom: 2px solid #333; padding-bottom: 20px; display: none; }
    .report-header h1 { font-size: 24px; font-weight: 700; margin: 0; text-transform: uppercase; color: #000; }
    .report-header h2 { font-size: 16px; font-weight: 500; margin: 5px 0 0 0; color: #333; }
    .report-meta { display: flex; justify-content: space-between; margin-bottom: 25px; font-size: 14px; color: #444; border-bottom: 1px solid #eee; padding-bottom: 10px; }
    .section-title { font-size: 16px; font-weight: 700; text-transform: uppercase; margin: 30px 0 15px 0; color: #222; border-left: 4px solid var(--bs-primary); padding-left: 10px; }
    
    /* Table Styles */
    .formal-table { width: 100%; border-collapse: collapse; margin-bottom: 20px; font-size: 13px; }
    .formal-table th, .formal-table td { border: 1px solid #ddd; padding: 10px 12px; text-align: left; }
    .formal-table th { background-color: #f8f9fa; font-weight: 700; text-transform: uppercase; color: #333; }
    .formal-table tr:nth-child(even) { background-color: #fafafa; }
    
    .text-right { text-align: right !important; }
    .text-center { text-align: center !important; }
    .font-bold { font-weight: 700; }
    .summary-grid { display: grid; grid-template-columns: repeat(2, 1fr); gap: 20px; margin-bottom: 30px; }
    .dropdown-menu-right { right: 0; left: auto; }

    /* CHART STYLES */
    .chart-wrapper {
        position: relative;
        height: 250px;
        width: 100%;
        background: #fff;
        border: 1px solid #eee;
        border-radius: 6px;
        padding: 10px;
        margin-bottom: 20px;
    }
    .chart-grid {
        display: grid;
        grid-template-columns: 1fr 1fr;
        gap: 20px;
        margin-bottom: 30px;
    }
    .chart-full-width {
        grid-column: span 2;
    }

    @media print {
        @page { margin: 1cm; size: A4; }
        body { background: #fff; -webkit-print-color-adjust: exact; print-color-adjust: exact; }
        .navbar, .sidebar, .screen-controls, .btn, footer, .page-header-actions { display: none !important; }
        .report-container { box-shadow: none; padding: 0; max-width: 100%; margin: 0; }
        .report-header { display: block !important; }
        .section-title { border-left: 4px solid #000 !important; }
        .formal-table th { background-color: #eee !important; color: #000; border: 1px solid #000; }
        .formal-table td { border: 1px solid #000; color: #000; }
        .summary-grid { grid-template-columns: 1fr 1fr; }
        .print-footer { position: fixed; bottom: 0; width: 100%; text-align: center; font-size: 10px; color: #666; border-top: 1px solid #ccc; padding-top: 5px; }
        
        /* Print Adjustments for Charts */
        .chart-wrapper { border: 0; height: 200px; page-break-inside: avoid; }
        .chart-grid { gap: 10px; margin-bottom: 10px; }
    }
</style>

<div class="container-fluid mt-4">
    
    <div class="screen-controls d-flex justify-content-between align-items-end flex-wrap gap-3">
        <form method="GET" class="d-flex gap-3 align-items-end flex-grow-1">
            <div class="form-group mb-0">
                <label class="small text-muted mb-1">From Date</label>
                <input type="date" name="date_from" class="form-control" value="<?= $date_from ?>" required>
            </div>
            <div class="form-group mb-0">
                <label class="small text-muted mb-1">To Date</label>
                <input type="date" name="date_to" class="form-control" value="<?= $date_to ?>" required>
            </div>
            <button type="submit" class="btn btn-primary"><i class="bi bi-filter"></i> Generate</button>
        </form>

        <div class="d-flex gap-2 page-header-actions">
            <button onclick="window.print()" class="btn btn-secondary"><i class="bi bi-printer"></i> Print Report</button>
            <div class="dropdown">
                <button class="btn btn-success dropdown-toggle" type="button" data-bs-toggle="dropdown">
                    <i class="bi bi-download"></i> Export Data
                </button>
                <ul class="dropdown-menu dropdown-menu-right">
                    <li><a class="dropdown-item" href="?export=summary&date_from=<?= $date_from ?>&date_to=<?= $date_to ?>">Summary Report (.csv)</a></li>
                    <li><a class="dropdown-item" href="?export=requests&date_from=<?= $date_from ?>&date_to=<?= $date_to ?>">Requests Data (.csv)</a></li>
                    <li><a class="dropdown-item" href="?export=penalties&date_from=<?= $date_from ?>&date_to=<?= $date_to ?>">Penalties Data (.csv)</a></li>
                </ul>
            </div>
        </div>
    </div>

    <div class="report-container">
        
        <div class="report-header">
            <h1>College of Science and Mathematics</h1>
            <h2>Apparatus Management System - Official Report</h2>
        </div>

        <div class="report-meta">
            <div>
                <strong>Generated By:</strong> <?= htmlspecialchars($_SESSION['username'] ?? 'System Admin') ?><br>
                <strong>Date Printed:</strong> <?= date('F d, Y h:i A') ?>
            </div>
            <div class="text-right">
                <strong>Reporting Period:</strong><br>
                <?= date('M d, Y', strtotime($date_from)) ?> — <?= date('M d, Y', strtotime($date_to)) ?>
            </div>
        </div>

        <h3 class="section-title">I. Visual Analytics</h3>
        <div class="chart-grid">
            <div class="chart-wrapper">
                <h6 class="text-center small text-muted text-uppercase font-bold mb-2">Request Status Distribution</h6>
                <canvas id="statusChart"></canvas>
            </div>
            <div class="chart-wrapper">
                <h6 class="text-center small text-muted text-uppercase font-bold mb-2">Borrowing by Category</h6>
                <canvas id="categoryChart"></canvas>
            </div>
            <div class="chart-wrapper chart-full-width">
                <h6 class="text-center small text-muted text-uppercase font-bold mb-2">Request Volume Timeline</h6>
                <canvas id="trendChart"></canvas>
            </div>
        </div>

        <h3 class="section-title">II. Executive Summary</h3>
        <div class="summary-grid">
            <table class="formal-table">
                <thead><tr><th colspan="2">Transaction Statistics</th></tr></thead>
                <tbody>
                    <tr><td>Total Borrow Requests</td><td class="text-right font-bold"><?= number_format($total_requests) ?></td></tr>
                    <tr><td>Requests Approved</td><td class="text-right"><?= number_format($approved_requests) ?></td></tr>
                    <tr><td>Items Returned</td><td class="text-right"><?= number_format($returned_requests) ?></td></tr>
                    <tr><td>Approval Rate</td><td class="text-right"><?= $total_requests > 0 ? round(($approved_requests/$total_requests)*100, 1) . '%' : '0%' ?></td></tr>
                </tbody>
            </table>
            <table class="formal-table">
                <thead><tr><th colspan="2">Financial & Inventory Status</th></tr></thead>
                <tbody>
                    <tr><td>Total Penalties Recorded</td><td class="text-right font-bold">₱<?= number_format($penalties_sum, 2) ?></td></tr>
                    <tr><td>Total Apparatus Types</td><td class="text-right"><?= number_format($total_items) ?></td></tr>
                    <tr><td>Items Low in Stock (≤5)</td><td class="text-right" style="<?= $low_stock_count > 0 ? 'color: #d32f2f; font-weight:bold;' : '' ?>"><?= number_format($low_stock_count) ?></td></tr>
                    <tr><td>Current Overdue Returns</td><td class="text-right" style="<?= $overdue_count > 0 ? 'color: #d32f2f; font-weight:bold;' : '' ?>"><?= number_format($overdue_count) ?></td></tr>
                </tbody>
            </table>
        </div>

        <h3 class="section-title">III. Most Borrowed Apparatus</h3>
        <table class="formal-table">
            <thead>
                <tr>
                    <th width="10%">Rank</th>
                    <th width="50%">Apparatus Name</th>
                    <th width="20%">Category</th>
                    <th width="20%" class="text-right">Usage Count</th>
                </tr>
            </thead>
            <tbody>
                <?php 
                $rank = 1;
                if (mysqli_num_rows($top_items_query) > 0):
                    while ($row = mysqli_fetch_assoc($top_items_query)): 
                ?>
                    <tr>
                        <td class="text-center"><?= $rank++ ?></td>
                        <td><?= htmlspecialchars($row['name']) ?></td>
                        <td><?= htmlspecialchars($row['category']) ?></td>
                        <td class="text-right"><?= $row['total_borrowed'] ?></td>
                    </tr>
                <?php endwhile; else: ?>
                    <tr><td colspan="4" class="text-center">No data found for this period.</td></tr>
                <?php endif; ?>
            </tbody>
        </table>

        <?php if ($overdue_count > 0): ?>
        <h3 class="section-title" style="border-left-color: #d32f2f;">IV. Overdue Items (Action Required)</h3>
        <table class="formal-table">
            <thead>
                <tr>
                    <th>Req ID</th>
                    <th>Student Name</th>
                    <th>Apparatus</th>
                    <th>Due Date</th>
                    <th>Days Delayed</th>
                </tr>
            </thead>
            <tbody>
                <?php while ($row = mysqli_fetch_assoc($overdue_list_query)): 
                    $due = new DateTime($row['date_needed']);
                    $now = new DateTime();
                    $diff = $now->diff($due);
                ?>
                    <tr>
                        <td>#<?= $row['request_id'] ?></td>
                        <td><?= htmlspecialchars($row['student']) ?></td>
                        <td><?= htmlspecialchars($row['apparatus']) ?></td>
                        <td><?= date('M d, Y', strtotime($row['date_needed'])) ?></td>
                        <td style="color: #d32f2f; font-weight: bold;"><?= $diff->days ?> Days</td>
                    </tr>
                <?php endwhile; ?>
            </tbody>
        </table>
        <?php endif; ?>

        <div class="print-footer d-none d-print-block">
            CSM Apparatus Management System | Report Generated Automatically | Page <span class="page-number"></span>
        </div>
    </div>
</div>

<script>
    // Configuration for a clean, formal look
    Chart.defaults.font.family = "'Segoe UI', 'Helvetica Neue', 'Arial', sans-serif";
    Chart.defaults.color = '#444';
    
    // 1. Status Chart (Doughnut)
    const ctxStatus = document.getElementById('statusChart').getContext('2d');
    new Chart(ctxStatus, {
        type: 'doughnut',
        data: {
            labels: ['Approved', 'Returned', 'Rejected', 'Pending'],
            datasets: [{
                data: [
                    <?= $chart_status_data['Approved'] ?>, 
                    <?= $chart_status_data['Returned'] ?>, 
                    <?= $chart_status_data['Rejected'] ?>, 
                    <?= $chart_status_data['Pending'] ?>
                ],
                backgroundColor: ['#4caf50', '#2196f3', '#f44336', '#ff9800'],
                borderWidth: 1
            }]
        },
        options: {
            responsive: true,
            maintainAspectRatio: false,
            plugins: {
                legend: { position: 'right', labels: { boxWidth: 12 } }
            }
        }
    });

    // 2. Trend Chart (Line)
    const ctxTrend = document.getElementById('trendChart').getContext('2d');
    new Chart(ctxTrend, {
        type: 'line',
        data: {
            labels: <?= json_encode($trend_labels) ?>,
            datasets: [{
                label: 'Requests Per Day',
                data: <?= json_encode($trend_data) ?>,
                borderColor: '#3f51b5',
                backgroundColor: 'rgba(63, 81, 181, 0.1)',
                borderWidth: 2,
                fill: true,
                tension: 0.3 // Smooth curves
            }]
        },
        options: {
            responsive: true,
            maintainAspectRatio: false,
            scales: {
                y: { beginAtZero: true, ticks: { precision: 0 } },
                x: { grid: { display: false } }
            },
            plugins: { legend: { display: false } }
        }
    });

    // 3. Category Chart (Bar)
    const ctxCat = document.getElementById('categoryChart').getContext('2d');
    new Chart(ctxCat, {
        type: 'bar',
        data: {
            labels: <?= json_encode($cat_labels) ?>,
            datasets: [{
                label: 'Usage Count',
                data: <?= json_encode($cat_data) ?>,
                backgroundColor: '#009688',
                borderRadius: 4
            }]
        },
        options: {
            indexAxis: 'y', // Horizontal Bar
            responsive: true,
            maintainAspectRatio: false,
            scales: {
                x: { beginAtZero: true, ticks: { precision: 0 } },
                y: { grid: { display: false } }
            },
            plugins: { legend: { display: false } }
        }
    });
</script>

<?php require_once __DIR__ . '/includes/footer.php'; ?>